Version 8 og CI, added automated EC2 deplyoment via AWS OIDC and SSM.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,6 +10,10 @@ jobs:
   test:
     runs-on: ubuntu-latest
 
+    permissions:
+      id-token: write
+      contents: read
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -43,3 +47,50 @@ jobs:
           tags: |
             c270sparkleteam2/sparkle:latest
             c270sparkleteam2/sparkle:${{ github.sha }}
+
+      - name: Configure AWS credentials
+        if: github.event_name == 'push'
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::891858635640:role/SparkleGitHubActionsRole
+          aws-region: ap-southeast-1
+
+      - name: Deploy to EC2 via SSM
+        if: github.event_name == 'push'
+        shell: bash
+        run: |
+          CMD_ID=$(aws ssm send-command \
+            --instance-ids i-01cfeb68e8fa7700f \
+            --document-name AWS-RunShellScript \
+            --parameters 'commands=["sudo -u ubuntu /home/ubuntu/deploy.sh"]' \
+            --query "Command.CommandId" \
+            --output text)
+
+          echo "Command ID: $CMD_ID"
+
+          aws ssm wait command-executed \
+            --command-id "$CMD_ID" \
+            --instance-id i-01cfeb68e8fa7700f || true
+
+          echo "===== Deployment Output ====="
+
+          aws ssm get-command-invocation \
+            --command-id "$CMD_ID" \
+            --instance-id i-01cfeb68e8fa7700f \
+            --query "StandardOutputContent" \
+            --output text
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$CMD_ID" \
+            --instance-id i-01cfeb68e8fa7700f \
+            --query "Status" \
+            --output text)
+
+          echo "Deployment Status: $STATUS"
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "Deployment failed."
+            exit 1
+          fi
+
+          echo "Deployment completed successfully."
